---
- name: Install packages
  apt: name={{item}} state=latest
  with_items:
    - python3-pip
    - python3-venv
    - python3-setuptools
    - python3-dev
  tags: [ "packages" ]

- name: Install virtualenv
  pip:
    name: virtualenv
    executable: pip3
  tags: [ "packages" ]
