---
- name: Install Supervisor
  apt: name={{item}} state=present
  with_items:
    - supervisor
    - curl
  tags: [ "packages" ]

- name: Copy application
  copy:
    src: "{{ app_dir }}"
    dest: "{{ app_dest }}"
    mode: 0755
  notify: Restart Supervisor
  tags: [ "configure" ]

- name: Setup python virtualenv
  pip: requirements={{ app_dest }}/{{ app_dir }}/{{ requirements_file }} virtualenv={{ venv_path }}/.{{ app_name }}_venv virtualenv_python=/usr/bin/python3.6
  notify: Restart Supervisor
  tags: [ "configure" ]

- name: Copy startup script
  template:
    src: start.sh.j2
    dest: "{{ app_dest }}/{{ app_dir }}/start.sh"
    mode: '+x'
  tags: [ "configure" ]

- name: Copy Supervisor configuration
  template:
    src: supervisor_template.conf.j2
    dest: /etc/supervisor/conf.d/{{ app_name }}.conf
  notify: Reread Supervisor
  tags: [ "configure" ]

- name: Ensure supervisor is started
  service: name=supervisor state=started enabled=yes
  tags: [ "service" ]
