---
- name: Install Fail2Ban
  apt: name=fail2ban state=present
  tags: [ "packages" ]

- name: Check if PermitRootLogin already disabled
  shell: grep -c "^PermitRootLogin no" /etc/ssh/sshd_config || true
  register: permitrootlogin_present
  tags: [ "configure" ]

- name: Disable remote root login
  lineinfile: dest=/etc/ssh/sshd_config line="PermitRootLogin no"
  when: permitrootlogin_present.stdout == "0"
  notify: Restart ssh
  tags: [ "configure" ]

- name: Check if PasswordAuthentication is already disallowed
  shell: grep -c "^PasswordAuthentication no" /etc/ssh/sshd_config || true
  register: passwordauthentication_present
  tags: [ "configure" ]

- name: Disallow SSH password authentication
  lineinfile: dest=/etc/ssh/sshd_config line="PasswordAuthentication no"
  when: passwordauthentication_present.stdout == "0"
  notify: Restart ssh
  tags: [ "configure" ]

- name: Check if user is already allowed
  shell: grep -c "^AllowUsers ansible" /etc/ssh/sshd_config || true
  register: allowuser_present
  tags: [ "configure" ]

- name: Enable SSH Login for Specific Users Only
  lineinfile: dest=/etc/ssh/sshd_config line="AllowUsers ansible"
  when: allowuser_present.stdout == "0"
  notify: Restart ssh
  tags: [ "configure" ]

- name: Configure Fail2Ban
  copy: src=jail.local dest=/etc/fail2ban/ mode=0644
  notify: Restart fail2ban
  tags: [ "configure" ]

- name: Ensure fail2ban is started
  service: name=fail2ban state=started enabled=yes
  tags: [ "service" ]

- name: Copy sysctl.conf
  copy: src=sysctl.conf dest=/etc/ mode=0644
  tags: [ "configure" ]

- name: Apply sysctl settings
  shell: sysctl -p
  tags: [ "configure" ]

- name: Check if security limits are already added
  shell: grep -c "^ansible hard nproc" /etc/security/limits.conf || true
  register: limits_present
  tags: [ "configure" ]

- name: Set security limits
  lineinfile: dest=/etc/security/limits.conf line="ansible hard nproc {{ process_limit }}"
  when: limits_present.stdout == "0"
  tags: [ "configure" ]

- name: Check if nospoof is already enabled
  shell: grep -c "^nospoof on" /etc/host.conf || true
  register: nospoof_present
  tags: [ "configure" ]

- name: Guard against IP spoofing
  lineinfile: dest=/etc/host.conf line="nospoof on"
  when: nospoof_present.stdout == "0"
  tags: [ "configure" ]
