---
  - hosts: appserver
    become: true
    gather_facts: false
    roles:
      - server-hardening
      - python_essentials
      - { role: supervisor_deploy, app_dir: application, app_name: sliceit, app_command: 'gunicorn -c gunicorn_conf.py run:app' }
